name: CI

on: [push, pull_request]

env:
  EM_VERSION: 2.0.16
  EM_CACHE_FOLDER: 'emsdk-cache'
  CODECOV_TOKEN: '99959e57-0b92-48b4-bf55-559d43d41b58'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Ubuntu GCC,   os: ubuntu-latest,  compiler: g++,     arch: "64", cmakepp: "",        flags: "-DCMAKE_CXX_FLAGS=--coverage"}
        - { name: Ubuntu Clang, os: ubuntu-latest,  compiler: clang++, arch: "64", cmakepp: "",        flags: ""}
        - { name: Windows 32,   os: windows-latest, compiler: vs2019,  arch: "32", cmakepp: "",        flags: "-A Win32"}
        - { name: Windows 64,   os: windows-latest, compiler: vs2019,  arch: "64", cmakepp: "",        flags: "-A x64"}
        - { name: MacOS,        os: macos-latest,   compiler: clang++, arch: "64", cmakepp: "",        flags: ""}
        - { name: WebAssembly,  os: ubuntu-latest,  compiler: em++,    arch: "32", cmakepp: "emcmake", flags: "-DCMAKE_CXX_FLAGS=\"-s DISABLE_EXCEPTION_CATCHING=0\" -DCMAKE_CROSSCOMPILING_EMULATOR=node"}
        build-type:
        - Release
        - Debug

    name: ${{matrix.platform.name}} ${{matrix.build-type}}
    runs-on: ${{matrix.platform.os}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup Linux compiler
      if: runner.os == 'Linux'
      run: export CXX=${{matrix.platform.compiler}}

    - name: Setup Emscripten cache
      if: matrix.platform.compiler == 'em++'
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}

    - name: Setup Emscripten
      if: matrix.platform.compiler == 'em++'
      uses: mymindstorm/setup-emsdk@v7
      with:
        version: ${{env.EM_VERSION}}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ${{matrix.platform.cmakepp}} cmake .. -DCMAKE_BUILD_TYPE=${{matrix.build-type}} ${{matrix.platform.flags}} -DOUP_DO_TEST=1

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{matrix.build-type}} --parallel 2

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure

    - name: Compute Code Coverage
      if: runner.os == 'Linux' && ${{matrix.platform.compiler}} == 'g++' && ${{matrix.build-type}} == 'Debug'
      run: gcov ${{github.workspace}}/build/tests/CMakeFiles/oup_tests.dir/runtime_tests.cpp.gcda && bash <(curl -s https://codecov.io/bash)
